backend:
  name: github
  repo: AhmedBouamoud/Mdrsti
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "الدروس والمقالات"
    folder: "_posts"
    create: true

    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الصورة", name: "thumbnail", widget: "image"}
      - {label: "المحتوى", name: "body", widget: "markdown"}